<?php

return [
    'page' => [
        'meta_title' => 'LinguFranca Performans Sistemi | Kişiye Özel Dil Koçluğu',
        'meta_description' => 'LinguFranca Performans Sistemi ile genel İngilizce, IELTS ve PTE hazırlığını birebir uzman eğitmenler, esnek planlama ve performans takibiyle ilerlet.',
        'meta_keywords' => 'lingufranca performans sistemi, kişiye özel dil koçluğu, online ingilizce, ielts hazırlık, pte hazırlık, birebir ingilizce dersi',
        'eyebrow' => 'Kişiye özel dil koçluğu',
        'title' => 'Akıcı konuşma ya da hedef skor için tek bir performans sistemi',
        'lead' => 'LinguFranca Performans Sistemi; genel İngilizce, IELTS ve PTE hazırlığını birebir uzman eğitmen, canlı geri bildirim, esnek ders planlaması ve gerçek performans takibiyle ilerletmek için tasarlandı.',
        'hero_badges' => [
            '1-1 Türk & Native uzman eğitmen',
            '7/24 WhatsApp destek',
            'Esnek saat planlaması',
            'Rapor analiz ve süreç takibi',
        ],
        'hero_stats' => [
            ['value' => '3', 'label' => 'ayrı program akışı'],
            ['value' => '12', 'label' => 'taksite kadar ödeme'],
            ['value' => '13/15', 'label' => 'mevcut dönem doluluk'],
        ],
        'press_badges' => [
            'TV8 Röportajı',
            'Beyaz TV Röportajı',
            'CNN Türk Röportajı',
            'Gerçek öğrenci memnuniyeti videoları',
        ],
        'manifesto_eyebrow' => 'Neden LinguFranca',
        'manifesto_title' => 'Bu bir kurs akışı değil, performans odaklı bir gelişim sistemi',
        'manifesto_lead' => 'PDF sunumlarında tekrar eden ortak omurga net: rastgele içerik yerine kişisel analiz, disiplinli takip, aktif katılım ve sonuç odaklı bir yol haritası.',
        'value_points' => [
            [
                'title' => 'Kişiye özel plan ile başlar',
                'description' => 'Mevcut seviyeniz, hedefiniz, haftalık ayırabileceğiniz zaman ve önceki öğrenme deneyiminiz analiz edilir. Amaç doğru seviyeden ve doğru stratejiyle ilerlemektir.',
            ],
            [
                'title' => 'Süreç boyunca iletişim kopmaz',
                'description' => 'WhatsApp üzerinden hızlı soru cevap desteği, görev kontrolleri, anlık yönlendirme ve düzeltmeler aktif şekilde sağlanır. Süreç mentorluk desteğiyle ilerler.',
            ],
            [
                'title' => 'İlerleme ölçülür ve güncellenir',
                'description' => 'Konuşma akıcılığı, ifade netliği, kelime kapasitesi ya da sınav performansı belirli aralıklarla değerlendirilir. Süreç durağan kalmaz, optimize edilir.',
            ],
        ],
        'includes_eyebrow' => 'Programda neler var',
        'includes_title' => 'PDF içeriklerinin ortak vaatleri',
        'includes' => [
            'Birebir özel ders ve konuşma odaklı yapı',
            'Sınav müfredatı uyumlu çalışma blokları',
            'Kişisel hız ayarlaması ve sabit müfredat baskısının olmaması',
            'Kişiye özel esnek saat planlaması',
            '7/24 WhatsApp destek hattı',
            'Ödev takibi, süreç takibi ve rapor analizleri',
            '7/24 erişilebilir çalışma platformu ve çalışma kaynakları',
            'Mock exam ve detaylı performans analiz takibi',
        ],
        'fit_eyebrow' => 'Bu sistem kimler için',
        'fit_title' => 'Herkes için değil',
        'fit_lead' => 'Sunumlardaki dil çok net: kısa yol arayanlar için değil, istikrarlı çalışmaya hazır olanlar için tasarlandı.',
        'fit_for' => [
            'İngilizceyi gerçekten hayatına entegre etmek isteyenler',
            '“Anlıyorum ama konuşamıyorum” bariyerini kırmak isteyenler',
            'IELTS, TOEFL, PTE ya da YDS hedef puanı olanlar',
            'Düzenli geri bildirim ve performans takibi ile ilerlemek isteyenler',
            'Kişiye özel öğrenme planıyla çalışmayı tercih edenler',
            'Disiplinli ve sistemli ilerlemeye hazır olanlar',
        ],
        'fit_not_for' => [
            'Standart ve sabit müfredatla ilerlemek isteyenler',
            'Sürece aktif katılım göstermeye hazır olmayanlar',
            'Hızlı ve zahmetsiz sonuç beklentisi olanlar',
            'Kısa yol ya da sihirli çözüm arayanlar',
            'Sadece pasif içerik tüketerek ilerlemek isteyenler',
        ],
        'process_eyebrow' => 'Süreç',
        'process_title' => '4 basit ama disiplinli adım',
        'steps' => [
            [
                'title' => 'İlk tanışma ve analiz',
                'description' => 'Seviye, hedef, haftalık tempo ve önceki deneyim analiz edilir. Genel İngilizce için konuşma odakları, sınav programı için hedef band ve zayıf alan tespiti yapılır.',
            ],
            [
                'title' => 'Kişisel performans planı',
                'description' => 'Ders yapısı, haftalık görev sistemi, konuşma odakları ya da Reading, Listening, Writing, Speaking stratejileri sizin takviminize uygun şekilde tasarlanır.',
            ],
            [
                'title' => 'Sürekli iletişim ve geri bildirim',
                'description' => 'WhatsApp desteği, form kontrolü, speaking düzeltmeleri ve görev takibi ile süreç sadece ders saatine sıkışmaz.',
            ],
            [
                'title' => 'Düzenli performans takibi',
                'description' => 'Genel İngilizce tarafında akıcılık ve ifade netliği; sınav tarafında süre, doğruluk, band kriterleri ve baskı altındaki performans ölçülür.',
            ],
        ],
        'goals_eyebrow' => 'Hedefimiz net',
        'goal_words' => [
            'Akıcı Konuşma',
            'Net İfade',
            'İngilizce Kimliği',
            'Stratejik Düşünme',
            'Zaman Yönetimi',
            'Akademik İfade',
        ],
        'proof_eyebrow' => 'Basın ve öğrenci sesleri',
        'proof_title' => 'Zip dosyasındaki tüm videolar tek landing içinde',
        'proof_lead' => 'TV röportajları, vaka anlatıları ve öğrenci memnuniyeti videolarını aynı akıştan açabilirsiniz. Kartlara tıklanınca video modali çalışır.',
        'pricing_eyebrow' => 'Paketler ve ödeme',
        'pricing_title' => 'Şeffaf fiyat ve planlama yapısı',
        'pricing_lead' => 'Sunumlardaki paket ve ödeme bilgileri bu landing içinde görünür durumda. Fiyatlar +KDV olarak verilmiştir.',
        'packages' => [
            [
                'name' => '16 Ders Paketi',
                'price' => '24.000 TL + KDV',
                'unit' => '1.500 TL / ders',
                'note' => 'Kısa dönemli hızlanma ve ilk performans düzeni için giriş paketi.',
            ],
            [
                'name' => '48 Ders Paketi',
                'price' => '57.600 TL + KDV',
                'unit' => '1.200 TL / ders',
                'note' => 'Uzun vadeli performans gelişimi ve kalıcı dil kazanımı için önerilen paket.',
                'featured' => true,
            ],
        ],
        'pricing_notes' => [
            '1 ders 40 dakika olarak planlanır.',
            'Haftalık ders sayısı öğrencinin uygunluğuna ve hedeflerine göre esnek belirlenir.',
            'Ödemeler iyzico güvenli ödeme altyapısı üzerinden alınır.',
            'Kredi kartına 12 taksite kadar ödeme imkânı sunulur.',
            'Program aynı anda sınırlı sayıda katılımcıyla yürütülür.',
        ],
        'faq' => [
            [
                'question' => 'Bu sayfadaki programlar kurs mantığında mı ilerliyor?',
                'answer' => 'Hayır. Sunumların ortak vurgusu bu yapının bir kurs modeli değil, kişiye özel tasarlanmış, performans odaklı ve disiplin gerektiren bir gelişim süreci olduğu yönünde.',
            ],
            [
                'question' => 'Genel İngilizce ile IELTS veya PTE hazırlığı aynı sistem içinde mi?',
                'answer' => 'Evet. Aynı performans sistemi çatısı altında genel İngilizce, IELTS ve PTE için ayrı çalışma akışları bulunuyor. Fark; içerik, ölçüm kriteri ve hedeflenen çıktı tarafında oluşuyor.',
            ],
            [
                'question' => 'Ders saatleri sabit mi?',
                'answer' => 'Hayır. PDF içeriğinde belirtildiği gibi haftalık ders sayısı ve saatler öğrencinin programına ve öğrenme hedefine göre esnek şekilde planlanıyor.',
            ],
            [
                'question' => 'Program boyunca ek destek var mı?',
                'answer' => 'Evet. WhatsApp üzerinden hızlı soru cevap, görev kontrolü, speaking veya form geribildirimi ve süreç yönlendirmesi aktif şekilde sağlanıyor.',
            ],
            [
                'question' => 'Başlamak için ilk adım ne olmalı?',
                'answer' => 'Önce hedefinizi netleştirip seviye tespiti yapmanız en doğru başlangıç olur. Ardından iletişime geçip size uygun program akışını netleştirebilirsiniz.',
            ],
        ],
        'cta_title' => 'Birlikte kendi performans planınızı netleştirelim',
        'cta_text' => 'Genel İngilizce, IELTS ya da PTE hedefiniz için doğru akışı seçin; sonra seviye tespiti ve iletişim adımından süreci başlatın.',
    ],
    'downloads' => [
        [
            'title' => 'LinguFranca Genel İngilizce',
            'subtitle' => 'Akıcı konuşma, net ifade ve özgüvenli İngilizce kimliği',
            'cover_asset' => 'general-cover',
            'file_asset' => 'general-pdf',
            'meta' => '23 sayfa PDF',
            'bullets' => [
                '1-1 Türk & Native uzman eğitmen',
                'Konuşma odaklı yapı ve aktif üretim',
                'Kişiye özel performans planı',
            ],
        ],
        [
            'title' => 'IELTS / TOEFL / YDS Sınav Programı',
            'subtitle' => 'Band hedefi, zaman yönetimi ve stratejik sınav performansı',
            'cover_asset' => 'ielts-cover',
            'file_asset' => 'ielts-pdf',
            'meta' => '30 sayfa PDF',
            'bullets' => [
                '7/24 erişilebilir çalışma platformu',
                'Sınırsız mock exam imkânı',
                'Detaylı performans analizi ve gelişim takibi',
            ],
        ],
        [
            'title' => 'PTE Academic Programı',
            'subtitle' => 'Hedefli çalışma, strateji videoları ve sınav becerileri modülleri',
            'cover_asset' => 'pte-cover',
            'file_asset' => 'pte-pdf',
            'meta' => '30 sayfa PDF',
            'bullets' => [
                'PTE öğrencilerine özel çalışma kaynakları',
                'Zaman baskısı altında performans optimizasyonu',
                'Essay yapısı ve speaking strateji çerçevesi',
            ],
        ],
    ],
    'media_library' => [
        [
            'category' => 'Basın',
            'title' => 'Beyaz TV Röportajı',
            'description' => 'LinguFranca yaklaşımının ekrana taşındığı uzun form medya kaydı.',
            'duration' => '05:18',
            'file_asset' => 'beyaz-tv-video',
        ],
        [
            'category' => 'Basın',
            'title' => 'TV8 Röportajı',
            'description' => 'Program yapısını ve yaklaşımı daha geniş formatta anlatan medya kaydı.',
            'duration' => '06:00',
            'file_asset' => 'tv8-video',
        ],
        [
            'category' => 'Basın',
            'title' => 'CNN Türk Röportajı',
            'description' => 'Kısa yayın formatında marka görünürlüğü ve anlatı kaydı.',
            'duration' => '02:04',
            'file_asset' => 'cnn-video',
        ],
        [
            'category' => 'Öğrenci Memnuniyeti',
            'title' => 'Ezgi Aze',
            'description' => 'Öğrenci memnuniyeti videosu.',
            'duration' => '00:50',
            'file_asset' => 'ezgi-video',
        ],
        [
            'category' => 'Öğrenci Memnuniyeti',
            'title' => 'Furkan Kanadmış',
            'description' => 'Öğrenci memnuniyeti videosu.',
            'duration' => '00:50',
            'file_asset' => 'furkan-video',
        ],
        [
            'category' => 'Öğrenci Memnuniyeti',
            'title' => '@gizzzemmmmm',
            'description' => 'Kısa öğrenci memnuniyeti kaydı.',
            'duration' => '00:43',
            'file_asset' => 'gizem-video',
        ],
    ],
    'assets' => [
        'general-pdf' => [
            'directory' => 'tmp/lingufranca_barista_assets',
            'extension' => 'pdf',
            'tokens' => ['lingufranca', 'genel'],
        ],
        'ielts-pdf' => [
            'directory' => 'tmp/lingufranca_barista_assets',
            'extension' => 'pdf',
            'tokens' => ['ielts', 'performans'],
        ],
        'pte-pdf' => [
            'directory' => 'tmp/lingufranca_barista_assets',
            'extension' => 'pdf',
            'tokens' => ['pte', 'performans'],
        ],
        'general-cover' => [
            'directory' => 'output/lingufranca_asset_audit',
            'extension' => 'png',
            'tokens' => ['lingufranca', 'genel', 'page1'],
        ],
        'ielts-cover' => [
            'directory' => 'output/lingufranca_asset_audit',
            'extension' => 'png',
            'tokens' => ['ielts', 'page1'],
        ],
        'pte-cover' => [
            'directory' => 'output/lingufranca_asset_audit',
            'extension' => 'png',
            'tokens' => ['pte', 'page1'],
        ],
        'beyaz-tv-video' => [
            'directory' => 'tmp/lingufranca_barista_assets',
            'extension' => 'mp4',
            'tokens' => ['beyaz', 'tv'],
        ],
        'tv8-video' => [
            'directory' => 'tmp/lingufranca_barista_assets',
            'extension' => 'mp4',
            'tokens' => ['tv8'],
        ],
        'cnn-video' => [
            'directory' => 'tmp/lingufranca_barista_assets',
            'extension' => 'mp4',
            'tokens' => ['cnn'],
        ],
        'ezgi-video' => [
            'directory' => 'tmp/lingufranca_barista_assets',
            'extension' => 'mp4',
            'tokens' => ['ezgi', 'aze'],
        ],
        'furkan-video' => [
            'directory' => 'tmp/lingufranca_barista_assets',
            'extension' => 'mp4',
            'tokens' => ['furkan', 'kanad'],
        ],
        'gizem-video' => [
            'directory' => 'tmp/lingufranca_barista_assets',
            'extension' => 'mp4',
            'tokens' => ['gizzzemmmmm'],
        ],
    ],
];
