<?php

return [
    'page' => [
        'meta_title' => 'LinguFranca Performans Sistemi',
        'meta_description' => 'Genel İngilizce, IELTS ve PTE için birebir uzman eğitmen, esnek planlama, 7/24 destek ve performans takibiyle tasarlanan LinguFranca Performans Sistemi.',
        'meta_keywords' => 'lingufranca performans sistemi, genel ingilizce, ielts hazırlık, pte hazırlık, birebir online ingilizce, dil koçluğu',
        'eyebrow' => 'Kişiye özel dil koçluğu',
        'title' => 'Akıcı konuşma ya da hedef skor için dağınık dersler değil, performans sistemi',
        'lead' => 'Genel İngilizce, IELTS ve PTE için ortak omurga net: önce analiz, sonra kişisel plan, ardından disiplinli takip. Bu sayfa, tüm akışları tek yapıda ve gerçek medya kayıtlarıyla gösterir.',
        'hero_badges' => [
            '1-1 Türk & Native uzman eğitmen',
            '7/24 WhatsApp destek',
            'Esnek saat planlaması',
            'Performans takibi ve rapor analiz',
        ],
        'hero_stats' => [
            ['value' => '3', 'label' => 'ayrı program akışı'],
            ['value' => '1-1', 'label' => 'özel ders modeli'],
            ['value' => '12', 'label' => 'taksite kadar ödeme'],
            ['value' => '13/15', 'label' => 'mevcut dönem doluluk'],
        ],
        'top_links' => [
            ['label' => 'Programlar', 'href' => '#programlar'],
            ['label' => 'Sistem', 'href' => '#sistem'],
            ['label' => 'Videolar', 'href' => '#videolar'],
            ['label' => 'Fiyat', 'href' => '#fiyat'],
            ['label' => 'SSS', 'href' => '#sss'],
        ],
        'hero_quote_title' => 'PDF’lerin ortak vaadi',
        'hero_quote' => 'Akıcı konuşabilen, hızlı düşünebilen, kendini net ifade edebilen ya da zamanını stratejik kullanarak hedef banda çıkan bir İngilizce kimliği inşa etmek.',
        'press_badges' => [
            'TV8 Röportajı',
            'Beyaz TV Röportajı',
            'CNN Türk Röportajı',
            'Gerçek öğrenci memnuniyeti videoları',
        ],
        'manifesto_eyebrow' => 'Sistemin omurgası',
        'manifesto_title' => 'Bu sayfadaki her blok gerçek program omurgasına dayanır',
        'manifesto_lead' => 'Genel İngilizce, IELTS ve PTE akışlarında tekrar eden ana yapı; rastgele içerik değil, kişisel analiz, özel destek grubu, aktif üretim, düzenli geri bildirim ve sürdürülebilir ilerleme.',
        'manifesto_points' => [
            [
                'title' => 'Programın amacı',
                'description' => 'Genel İngilizce tarafında akıcı konuşma, hızlı düşünme ve net ifade; sınav tarafında ise sınav mantığı, zaman yönetimi ve stratejik performans öne çıkarılıyor. Amaç bilgi yığmak değil, somut çıktı üretmek.',
            ],
            [
                'title' => 'Performans ekibi',
                'description' => 'PDF’lerde açıkça verilen yapı aynı: Kurucu & Dil Koçu, Ana Eğitmen, Müfredat Sorumlusu ve Rehber Mentör. Her katılımcı için özel bir destek grubu kuruluyor.',
            ],
            [
                'title' => 'Şeffaf süreç anlayışı',
                'description' => 'Sunumlarda sansürlenmiş gerçek süreç örnekleri, görev akışları ve öğrenci geri bildirimleri kullanılıyor. Sayfadaki video bölümü de bu şeffaflık katmanını canlı şekilde taşıyor.',
            ],
        ],
        'resource_eyebrow' => 'Program içinde neler var',
        'resource_title' => 'Genel İngilizce ve sınav tarafında öne çıkan içerikler',
        'resource_columns' => [
            [
                'label' => 'Genel İngilizce omurgası',
                'items' => [
                    'Konuşma odaklı yapı ve aktif üretim',
                    'Sabit müfredat baskısı yerine öğrencinin temposuna göre planlama',
                    'Kelime kullanımı, ifade netliği ve akıcılık için düzenli ölçüm',
                    'WhatsApp üzerinden hızlı soru-cevap, ödev takibi ve anlık yönlendirme',
                    'Anlıyorum ama konuşamıyorum bariyerini kırmaya odaklanan özel ders akışı',
                ],
            ],
            [
                'label' => 'Sınav programı omurgası',
                'items' => [
                    'Hedef band / skor analizi ve bölüm bazlı zayıf alan tespiti',
                    'Reading, Listening, Writing ve Speaking için ayrı strateji çerçevesi',
                    'Band descriptor çözümlemesi, trap question analizi ve essay template sistemi',
                    'Academic vocabulary, scanning-skimming ve controlled speaking drills',
                    'Sınırsız mock exam, detaylı performans analizi ve gelişim takibi',
                ],
            ],
        ],
        'fit_eyebrow' => 'Bu sistem kimler için',
        'fit_title' => 'Herkes için değil',
        'fit_lead' => 'Sunumlardaki dil çok net: kısa yol arayanlar için değil, istikrarlı katılım gösterecek ve gerçek ilerleme isteyen katılımcılar için tasarlandı.',
        'fit_for' => [
            'İngilizceyi gerçekten hayatına entegre etmek isteyenler',
            'Anlıyorum ama konuşamıyorum bariyerini kırmak isteyenler',
            'IELTS, TOEFL, PTE veya YDS hedef puanı olanlar',
            'Düzenli geri bildirim ve performans takibiyle ilerlemek isteyenler',
            'Kişiye özel öğrenme planıyla çalışmayı tercih edenler',
            'Disiplinli ve sistemli ilerlemeye hazır olanlar',
        ],
        'fit_not_for' => [
            'Standart ve sabit müfredatla ilerlemek isteyenler',
            'Sürece aktif katılım göstermeye hazır olmayanlar',
            'Hızlı ve zahmetsiz sonuç beklentisi olanlar',
            'Kısa yol ya da sihirli çözüm arayanlar',
            'Sadece pasif içerik tüketerek ilerlemek isteyenler',
        ],
        'process_eyebrow' => 'Süreç',
        'process_title' => 'PDF’lerde anlatılan akış: 4 disiplinli adım',
        'steps' => [
            [
                'title' => 'İlk tanışma ve analiz',
                'description' => 'Mevcut seviye, haftalık uygunluk, önceki öğrenme deneyimi ve hedef netleştirilir. Sınav akışında ayrıca hedef band ve zayıf modüller analiz edilir.',
            ],
            [
                'title' => 'Kişisel performans planı',
                'description' => 'Ders yapısı, konuşma odakları, görev sistemi ya da sınav tarafında Writing, Speaking ve zaman yönetimi planı kişiye göre belirlenir.',
            ],
            [
                'title' => 'Sürekli iletişim ve geri bildirim',
                'description' => 'WhatsApp desteği, görev kontrolleri, form ve speaking geri bildirimleri sayesinde süreç sadece ders saatine sıkışmaz.',
            ],
            [
                'title' => 'Düzenli performans takibi',
                'description' => 'Genel İngilizce için akıcılık ve ifade netliği; sınav tarafı için süre, doğruluk, band kriterleri ve baskı altındaki performans sürekli güncellenir.',
            ],
        ],
        'milestones_eyebrow' => 'Hedefimiz net',
        'milestones' => [
            [
                'label' => 'Genel İngilizce hedefleri',
                'items' => [
                    'Akıcı konuşma',
                    'Hızlı düşünme',
                    'Net ifade',
                    'Özgüvenli İngilizce kimliği',
                ],
            ],
            [
                'label' => 'Sınav hedefleri',
                'items' => [
                    'Zaman yönetimi',
                    'Akademik ifade',
                    'Sınav kimliği',
                    'Stratejik düşünme',
                ],
            ],
        ],
        'reasons_eyebrow' => 'Neden şimdi başlamalısın',
        'reasons_title' => 'Sunumlardaki mesaj net: mükemmel zaman yok',
        'reasons' => [
            'Erteleme tuzağı',
            'İstikrarlı uygulama',
            'Çalışan plan kazandırır',
            '%80 istikrarlı uygulama = %100 sonuç',
        ],
        'proof_eyebrow' => 'Basın ve öğrenci videoları',
        'proof_title' => 'Basın ve öğrenci videoları bu sayfanın içinde',
        'proof_lead' => 'TV röportajları ve öğrenci memnuniyeti kayıtları posterli medya blokları halinde yer alıyor. Karttan videoyu açıp aynı akış içinde izleyebilirsiniz.',
        'pricing_eyebrow' => 'Paketler ve ödeme',
        'pricing_title' => 'Şeffaf fiyat yapısı',
        'pricing_lead' => 'Paket mantığı korunarak aktarıldı. Fiyatlar +KDV şeklindedir ve ödeme yapısı iyzico üzerinden 12 taksite kadar planlanabilir.',
        'packages' => [
            [
                'name' => '16 Ders Paketi',
                'price' => '24.000 TL + KDV',
                'unit' => '1.500 TL / ders',
                'note' => 'Kısa sürede ivme kazanmak, sistemi görmek ve ilk performans düzenini kurmak isteyenler için giriş paketi.',
            ],
            [
                'name' => '48 Ders Paketi',
                'price' => '57.600 TL + KDV',
                'unit' => '1.200 TL / ders',
                'note' => 'Kalıcı gelişim, düzenli tekrar ve hedef odaklı uzun soluklu sonuç için önerilen ana paket.',
                'featured' => true,
            ],
        ],
        'pricing_notes' => [
            '1 ders 40 dakika olarak planlanır.',
            'Haftalık ders sayısı öğrencinin uygunluğu ve hedeflerine göre esnek belirlenir.',
            'Ödemeler iyzico güvenli ödeme altyapısı üzerinden alınır.',
            'Kredi kartına 12 taksite kadar ödeme imkânı sunulur.',
            'Program aynı anda sınırlı sayıda katılımcıyla yürütülür.',
            'Her ay yalnızca sınırlı sayıda katılımcı kabul edilir.',
        ],
        'faq' => [
            [
                'question' => 'Bu sayfadaki yapı klasik kurs mantığında mı ilerliyor?',
                'answer' => 'Hayır. PDF’lerde açıkça vurgulanan yapı bir kurs akışı değil; kişiye özel plan, aktif takip, mentorluk desteği ve performans ölçümüyle ilerleyen bir sistem.',
            ],
            [
                'question' => 'Genel İngilizce ile IELTS veya PTE hazırlığı aynı sistem içinde mi?',
                'answer' => 'Evet. Aynı performans sistemi çatısı altında üç ayrı akış bulunuyor. Ortak omurga aynı, içerik ve ölçüm kriteri programa göre değişiyor.',
            ],
            [
                'question' => 'Ders saatleri sabit mi?',
                'answer' => 'Hayır. Sunumlarda belirtildiği gibi haftalık ders sayısı ve saatler öğrencinin temposuna, hedefine ve uygunluk durumuna göre esnek planlanıyor.',
            ],
            [
                'question' => 'Program boyunca ek destek var mı?',
                'answer' => 'Evet. WhatsApp üzerinden hızlı soru-cevap, görev kontrolü, speaking ya da form geribildirimi ve süreç yönlendirmesi sağlanıyor.',
            ],
            [
                'question' => 'Başlamak için ilk adım ne olmalı?',
                'answer' => 'Önce hedefiniz netleştirilir ve ön değerlendirme yapılır. Ardından sizin için doğru akış ve uygun program planı birlikte belirlenir.',
            ],
        ],
        'cta_title' => 'Kendi performans planınızı netleştirelim',
        'cta_text' => 'Genel İngilizce, IELTS ya da PTE hedefiniz için doğru akışı seçin; sonra seviye tespiti ve iletişim adımıyla süreci başlatın.',
    ],
    'downloads' => [
        [
            'label' => 'Genel İngilizce',
            'title' => 'LinguFranca Genel İngilizce',
            'subtitle' => 'Akıcı konuşma, net ifade ve özgüvenli İngilizce kimliği',
            'cover_asset' => 'general-cover',
            'file_asset' => 'general-pdf',
            'meta' => '23 sayfa PDF',
            'result' => 'Anlıyorum ama konuşamıyorum bariyerini kırmak',
            'bullets' => [
                'Konuşma odaklı yapı ve aktif üretim',
                'Kişiye özel esnek saat planlaması',
                'Sabit müfredat baskısı olmadan seviye bazlı ilerleme',
            ],
        ],
        [
            'label' => 'IELTS / TOEFL / YDS',
            'title' => 'LinguFranca Sınav Programı',
            'subtitle' => 'Band hedefi, zaman yönetimi ve stratejik sınav performansı',
            'cover_asset' => 'ielts-cover',
            'file_asset' => 'ielts-pdf',
            'meta' => '26 sayfa PDF',
            'result' => 'Hedef band için ölçülebilir sınav planı',
            'bullets' => [
                'IELTS öğrencilerine özel çalışma kaynakları',
                'Sınırsız mock exam ve gelişim takibi',
                'Reading, Listening, Writing, Speaking için stratejik modüller',
            ],
        ],
        [
            'label' => 'PTE Academic',
            'title' => 'PTE Academic Programı',
            'subtitle' => 'Strateji videoları, pratik materyaller ve hedefli çalışma planı',
            'cover_asset' => 'pte-cover',
            'file_asset' => 'pte-pdf',
            'meta' => '25 sayfa PDF',
            'result' => 'Zaman baskısı altında performans optimizasyonu',
            'bullets' => [
                'PTE öğrencilerine özel kaynak ve şablonlar',
                'Strateji videoları ile hedefli çalışma',
                'Speaking, writing ve puan mantığı için sistemli planlama',
            ],
        ],
    ],
    'media_library' => [
        [
            'category' => 'Basın',
            'title' => 'Beyaz TV Röportajı',
            'description' => 'LinguFranca yaklaşımının televizyon yayınındaki uzun form anlatımı.',
            'duration' => '05:18',
            'file_asset' => 'beyaz-tv-video',
            'poster_asset' => 'beyaz-tv-poster',
        ],
        [
            'category' => 'Basın',
            'title' => 'TV8 Röportajı',
            'description' => 'Program yapısını ve sistem mantığını daha geniş formatta anlatan yayın kaydı.',
            'duration' => '06:00',
            'file_asset' => 'tv8-video',
            'poster_asset' => 'tv8-poster',
        ],
        [
            'category' => 'Basın',
            'title' => 'CNN Türk Röportajı',
            'description' => 'Marka görünürlüğü ve yaklaşımın kısa yayın formatındaki anlatımı.',
            'duration' => '02:04',
            'file_asset' => 'cnn-video',
            'poster_asset' => 'cnn-turk-poster',
        ],
        [
            'category' => 'Öğrenci Memnuniyeti',
            'title' => 'Ezgi Aze',
            'description' => 'Gerçek öğrenci deneyimini kısa ve doğrudan anlatan memnuniyet kaydı.',
            'duration' => '00:50',
            'file_asset' => 'ezgi-video',
            'poster_asset' => 'ezgi-aze-poster',
        ],
        [
            'category' => 'Öğrenci Memnuniyeti',
            'title' => 'Furkan Kanadmış',
            'description' => 'Programın birebir takip tarafını yansıtan öğrenci geri bildirimi.',
            'duration' => '00:50',
            'file_asset' => 'furkan-video',
            'poster_asset' => 'furkan-kanadmis-poster',
        ],
        [
            'category' => 'Öğrenci Memnuniyeti',
            'title' => '@gizzzemmmmm',
            'description' => 'Kısa formatta öğrenci memnuniyetini gösteren sosyal kanıt videosu.',
            'duration' => '00:43',
            'file_asset' => 'gizem-video',
            'poster_asset' => 'gizem-poster',
        ],
    ],
    'assets' => [
        'general-pdf' => [
            'directory' => 'public/uploads/lingufranca-performance/pdfs',
            'extension' => 'pdf',
            'tokens' => ['general', 'english'],
        ],
        'ielts-pdf' => [
            'directory' => 'public/uploads/lingufranca-performance/pdfs',
            'extension' => 'pdf',
            'tokens' => ['ielts', 'exam'],
        ],
        'pte-pdf' => [
            'directory' => 'public/uploads/lingufranca-performance/pdfs',
            'extension' => 'pdf',
            'tokens' => ['pte', 'exam'],
        ],
        'general-cover' => [
            'directory' => 'public/uploads/lingufranca-performance/covers',
            'extension' => 'png',
            'tokens' => ['general', 'cover'],
        ],
        'ielts-cover' => [
            'directory' => 'public/uploads/lingufranca-performance/covers',
            'extension' => 'png',
            'tokens' => ['ielts', 'cover'],
        ],
        'pte-cover' => [
            'directory' => 'public/uploads/lingufranca-performance/covers',
            'extension' => 'png',
            'tokens' => ['pte', 'cover'],
        ],
        'beyaz-tv-video' => [
            'directory' => 'public/uploads/lingufranca-performance/videos',
            'extension' => 'mp4',
            'tokens' => ['beyaz', 'preview'],
        ],
        'tv8-video' => [
            'directory' => 'public/uploads/lingufranca-performance/videos',
            'extension' => 'mp4',
            'tokens' => ['tv8', 'preview'],
        ],
        'cnn-video' => [
            'directory' => 'public/uploads/lingufranca-performance/videos',
            'extension' => 'mp4',
            'tokens' => ['cnn', 'preview'],
        ],
        'ezgi-video' => [
            'directory' => 'public/uploads/lingufranca-performance/videos',
            'extension' => 'mp4',
            'tokens' => ['ezgi', 'preview'],
        ],
        'furkan-video' => [
            'directory' => 'public/uploads/lingufranca-performance/videos',
            'extension' => 'mp4',
            'tokens' => ['furkan', 'preview'],
        ],
        'gizem-video' => [
            'directory' => 'public/uploads/lingufranca-performance/videos',
            'extension' => 'mp4',
            'tokens' => ['gizem', 'preview'],
        ],
        'beyaz-tv-poster' => [
            'directory' => 'public/uploads/lingufranca-performance/posters',
            'extension' => 'jpg',
            'tokens' => ['beyaz', 'tv', 'poster'],
        ],
        'tv8-poster' => [
            'directory' => 'public/uploads/lingufranca-performance/posters',
            'extension' => 'jpg',
            'tokens' => ['tv8', 'poster'],
        ],
        'cnn-turk-poster' => [
            'directory' => 'public/uploads/lingufranca-performance/posters',
            'extension' => 'jpg',
            'tokens' => ['cnn', 'poster'],
        ],
        'ezgi-aze-poster' => [
            'directory' => 'public/uploads/lingufranca-performance/posters',
            'extension' => 'jpg',
            'tokens' => ['ezgi', 'poster'],
        ],
        'furkan-kanadmis-poster' => [
            'directory' => 'public/uploads/lingufranca-performance/posters',
            'extension' => 'jpg',
            'tokens' => ['furkan', 'poster'],
        ],
        'gizem-poster' => [
            'directory' => 'public/uploads/lingufranca-performance/posters',
            'extension' => 'jpg',
            'tokens' => ['gizem', 'poster'],
        ],
    ],
];
